<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>L2Editor</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>true</StripSymbols>
    <TrimmerRootDescriptor>false</TrimmerRootDescriptor>
    <ApplicationIcon>images\favicon_ico.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="images\favicon_ico.ico" />
  </ItemGroup>
</Project>
